#!/bin/sh

Result_Path=`pwd`/result

NAS_CLI_Tool_Path=`pwd`/cli

gcc_path=`pwd`/tools/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin

cd $NAS_CLI_Tool_Path
#Application
$gcc_path/arm-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o NAS_CLI_Tool NAS_CLI_Tool.c -I ../inc -lpthread

if [ -e NAS_CLI_Tool ]
then
	cp NAS_CLI_Tool $Result_Path
	rm NAS_CLI_Tool
fi

#cd $Log_Path
#$gcc_path/arm-cortexa9-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o nm nm.c common.c md5.c
#if [ -e nm ]
#then
#    cp nm $Result_Path
#    rm nm
#fi


