#!/bin/sh

Result_Path=`pwd`/result

Log_Path=`pwd`/cli

gcc_path=`pwd`/tools/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin

cd $Log_Path
pwd
#Application
$gcc_path/arm-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o logmain logmain.c -I ../inc -lpthread

if [ -e logmain ]
then
	cp logmain $Result_Path
	rm logmain
fi

#cd $Log_Path
#$gcc_path/arm-cortexa9-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o nm nm.c common.c md5.c
#if [ -e nm ]
#then
#    cp nm $Result_Path
#    rm nm
#fi


