#!/bin/sh

Result_Path=`pwd`/result

Cli_Path=`pwd`/cli






cd $Cli_Path

$gcc_path/arm-cortexa9-linux-gnueabihf-g++  -O2 -Wall -DLINUX -o cli cli.c -I ../inc -lpthread


if [ -e cli ]
then
	cp cli $Result_Path
	rm cli
	echo "~~~cli~ok~~~~"
fi

