#!/bin/sh

GCC_PATH=/opt/arm-cortexa9-linux-gnueabihf/gcc-4.7.3-glibc-2.16.0-binutils-2.22-kernel-3.6-sanitized/bin
RESULT_PATH=`pwd`/result
PROTOCOL_PATH=`pwd`/protocol
CLI_PATH=`pwd`/cli
ROUTE_PATH=`pwd`/adapter

Adapter_Path=`pwd`/adapter


cd $PROTOCOL_PATH
$GCC_PATH/arm-cortexa9-linux-gnueabihf-g++  -O2 -Wall -DLINUX -o sap \
                                sap.c \
                                dll.c \
                                dll_algrthm.c \
                                dll_idp.c \
                                dll_odp.c \
                                dll_interleave.c \
                                ccl_dl.c \
                                ccl_ul.c \
                                ccl_thread.c \
                                ccl_fun.c \
                                print_debug.c \
                                -I ../inc -lpthread

if [ -e sap ]
then

    cp sap $RESULT_PATH
    rm sap
    echo ""
    echo "~~~sap~ok~~~~"
    echo ""
fi



cd $CLI_PATH
$GCC_PATH/arm-cortexa9-linux-gnueabihf-g++  -O2 -Wall -DLINUX -o cli cli.c -I ../inc -lpthread
if [ -e cli ]
then
    cp cli $RESULT_PATH
    rm cli
    echo ""
    echo "~~~cli~ok~~~~"
    echo ""
fi



cd $ROUTE_PATH
$GCC_PATH/arm-cortexa9-linux-gnueabihf-g++  -O2 -Wall -DLINUX -o route route.c -I ../inc -lpthread
if [ -e route ]
then
   cp route $RESULT_PATH
   rm route
   echo ""
   echo "~~~~route~~ok~~"
   echo ""
fi


cd $CLI_PATH
$GCC_PATH/arm-cortexa9-linux-gnueabihf-g++  -O2 -Wall -DLINUX -o logmain logmain.c -I ../inc -lpthread

if [ -e logmain ]
then
	cp logmain $RESULT_PATH
	rm logmain
	echo ""
	echo "~~~~logmain~~ok~~"
	echo ""
fi

